INFO:     Will watch for changes in these directories: ['C:\\Users\\issei\\Documents\\Dev\\api']
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
INFO:     Started reloader process [5220] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\issei\Documents\Dev\api\beta.py", line 31, in <module>
    from g4f.Provider import OpenaiChat, Gemini, You, Bing, GeminiProChat, Reka,Liaobots,GeminiPro
ImportError: cannot import name 'GeminiProChat' from 'g4f.Provider' (C:\Users\issei\Documents\Dev\api\g4f\Provider\__init__.py)
WARNING:  StatReload detected changes in 'beta.py'. Reloading...
WARNING:  StatReload detected changes in 'beta.py'. Reloading...
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\issei\Documents\Dev\api\.venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\issei\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\issei\Documents\Dev\api\beta.py", line 31, in <module>
    from g4f.Provider import Gemini
ImportError: cannot import name 'Gemin' from 'g4f.Provider' (C:\Users\issei\Documents\Dev\api\g4f\Provider\__init__.py)
INFO:     Started server process [8956]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
None
INFO:     127.0.0.1:24790 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:24790 - "GET /home/css/icon.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:24791 - "POST /create_token HTTP/1.1" 200 OK
INFO:     127.0.0.1:24793 - "GET /generate_image?prompt=%E7%8C%AB%E3%81%8C%E8%BA%8D%E3%82%8B%0A HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:24845 - "GET / HTTP/1.1" 200 OK
ERROR:root:Error occurred: Install "nest_asyncio" package
Read .har file: C:\Users\issei\Documents\Dev\api\har\gemini.google.com.har
Read .har file: C:\Users\issei\Documents\Dev\api\har\huggingface.co.har
Cookies added: 3 from huggingface.co
Read cookie file: C:\Users\issei\Documents\Dev\api\har\gemini.google.com.json
Cookies added: 17 from .google.com
Cookies added: 3 from .gemini.google.com
Read cookie file: C:\Users\issei\Documents\Dev\api\har\rika.json
Cookies added: 1 from chat.reka.ai
Using Ai4Chat provider and default model
INFO:     127.0.0.1:24846 - "POST /chat HTTP/1.1" 200 OK
ERROR:root:Error occurred: Install "nest_asyncio" package
ERROR:root:Error occurred: Install "nest_asyncio" package
Using MagickPen provider and default model
Using FreeNetfly provider and gpt-3.5-turbo model
INFO:     127.0.0.1:24847 - "POST /chat HTTP/1.1" 200 OK
